FileVersion = 1
Projects = {SteelEngine = {Path = "Engine"}, SteelEditor = {Path = "Editor"}, glfw-beef = {Path = "Libs/GLFW"}, BasicSteelGame = {Path = "Examples/BasicSteelGame"}, Bgfx = {Path = "Libs/BGFX"}, libpng = {Path = "Libs/libpng"}, tinyobjloader = {Path = "Libs/tinyobjloader"}, Launcher = {Path = "Launcher"}, FreeType = {Path = "FreeType"}}

[Workspace]
StartupProject = "Launcher"
