FileVersion = 1
Projects = {SteelEngine = {Path = "Engine"}, glfw-beef = {Path = "Libs/GLFW"}, BasicSteelGame = {Path = "Examples/BasicSteelGame"}, libpng = {Path = "Libs/libpng"}, tinyobjloader = {Path = "Libs/tinyobjloader"}, bgfx-beef = {Path = "Libs/bgfx-beef"}}

[Workspace]
StartupProject = "BasicSteelGame"
