FileVersion = 1
Dependencies = {corlib = "*", SteelEngine = "*"}

[Project]
Name = "BasicSteelGame"
StartupObject = "BasicSteelGame.Program"

[Configs.Debug.Win64]
DebugCommandArguments = "-project D:\\SteelEngine\\content\\"
